### ISSUE TITLE
SIGBUS while capturing zink

### ISSUE THREAD

**Issue by zmike** [LunarG/gfxreconstruct#736]
As of 13e8ee65c843e8539da4bacbcefe7806d55d68a0 I get this crash on startup when trying to run anything using zink+lavapipe:

`GFXRECON_PAGE_GUARD_UNBLOCK_SIGSEGV=true VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct LIBGL_ALWAYS_SOFTWARE=1 MESA_LOADER_DRIVER_OVERRIDE=zink gdb glxgears`

```
Thread 1 "glxgears" received signal SIGBUS, Bus error.
0x00007fffed61b76d in gfxrecon::encode::EncodePNextStruct(gfxrecon::encode::ParameterEncoder*, void const*) () from /usr/local/lib64/libVkLayer_gfxreconstruct.so
(gdb) bt
#0  0x00007fffed61b76d in gfxrecon::encode::EncodePNextStruct(gfxrecon::encode::ParameterEncoder*, void const*) () from /usr/local/lib64/libVkLayer_gfxreconstruct.so
#1  0x00007fffed61c169 in gfxrecon::encode::EncodePNextStruct(gfxrecon::encode::ParameterEncoder*, void const*) () from /usr/local/lib64/libVkLayer_gfxreconstruct.so
#2  0x00007fffed61c169 in gfxrecon::encode::EncodePNextStruct(gfxrecon::encode::ParameterEncoder*, void const*) () from /usr/local/lib64/libVkLayer_gfxreconstruct.so
#3  0x00007fffed67c1c1 in gfxrecon::encode::EncodeStruct(gfxrecon::encode::ParameterEncoder*, VkFormatProperties2 const&) () from /usr/local/lib64/libVkLayer_gfxreconstruct.so
#4  0x00007fffed62a983 in gfxrecon::encode::GetPhysicalDeviceFormatProperties2KHR(VkPhysicalDevice_T*, VkFormat, VkFormatProperties2*) () from /usr/local/lib64/libVkLayer_gfxreconstruct.so
#5  0x00007ffff7260811 in populate_format_props (screen=0x555555668390) at ../src/gallium/drivers/zink/zink_screen.c:1735
#6  0x00007ffff726253c in zink_internal_create_screen (config=0x7fffffffc3a0) at ../src/gallium/drivers/zink/zink_screen.c:2308
#7  0x00007ffff7262a5d in zink_create_screen (winsys=0x555555661de0, config=0x7fffffffc3a0) at ../src/gallium/drivers/zink/zink_screen.c:2389
#8  0x00007ffff5ca3957 in sw_screen_create_zink (winsys=0x555555661de0, config=0x7fffffffc3a0, whatever=false) at ../src/gallium/auxiliary/target-helpers/sw_helper.h:117
#9  0x00007ffff681972f in pipe_loader_sw_create_screen (dev=0x555555661d70, config=0x7fffffffc3a0, sw_vk=false) at ../src/gallium/auxiliary/pipe-loader/pipe_loader_sw.c:425
#10 0x00007ffff6819158 in pipe_loader_create_screen_vk (dev=0x555555661d70, sw_vk=false) at ../src/gallium/auxiliary/pipe-loader/pipe_loader.c:171
#11 0x00007ffff6819177 in pipe_loader_create_screen (dev=0x555555661d70) at ../src/gallium/auxiliary/pipe-loader/pipe_loader.c:177
#12 0x00007ffff5cb200d in kopper_init_screen (sPriv=0x55555565e8d0) at ../src/gallium/frontends/dri/kopper.c:159
#13 0x00007ffff5ca91bf in driCreateNewScreen2 (scrn=0, fd=-1, extensions=0x7ffff7e81840 <kopper_extensions_noshm>, driver_extensions=0x7ffff7942680 <galliumvk_driver_extensions>, driver_configs=0x7fffffffce98, data=0x55555555e6e0) at ../src/gallium/frontends/dri/dri_util.c:142
#14 0x00007ffff5ca9466 in driSWRastCreateNewScreen2 (scrn=0, extensions=0x7ffff7e81840 <kopper_extensions_noshm>, driver_extensions=0x7ffff7942680 <galliumvk_driver_extensions>, driver_configs=0x7fffffffce98, data=0x55555555e6e0) at ../src/gallium/frontends/dri/dri_util.c:213
#15 0x00007ffff7e37665 in driswCreateScreenDriver (screen=0, priv=0x55555555e500, driver=0x7ffff7e78ba0 "zink") at ../src/glx/drisw_glx.c:963
#16 0x00007ffff7e379ce in driswCreateScreen (screen=0, priv=0x55555555e500) at ../src/glx/drisw_glx.c:1040
#17 0x00007ffff7e3eef2 in AllocAndFetchScreenConfigs (dpy=0x55555555c330, priv=0x55555555e500) at ../src/glx/glxext.c:851
#18 0x00007ffff7e3f33f in __glXInitialize (dpy=0x55555555c330) at ../src/glx/glxext.c:976
#19 0x00007ffff7e3800c in GetGLXPrivScreenConfig (dpy=0x55555555c330, scrn=0, ppriv=0x7fffffffd148, ppsc=0x7fffffffd140) at ../src/glx/glxcmds.c:173
#20 0x00007ffff7e3a4b8 in glXChooseVisual (dpy=0x55555555c330, screen=0, attribList=0x7fffffffd260) at ../src/glx/glxcmds.c:1269
#21 0x0000555555558626 in make_window.constprop ()
#22 0x0000555555556999 in main ()
```

**Comment by panos-lunarg** [comment]
Which mesa revision are zink and llvmpipe using?

**Comment by zmike** [comment]
mesa @ d92c1ca01b3

**Comment by panos-lunarg** [comment]
OK can reproduce now. Looking into it
