### ISSUE TITLE
Linux validation errors capturing vkcube

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#771]
Ubuntu 20.04, vkconfig, "Frame Capture" configuration, enabling `VK_LAYER_KHRONOS_validation`, capturing vkcube (with F5 hot key) results in the following validation errors:
```
VUID-VkImageMemoryBarrier-oldLayout-01212(ERROR / SPEC): msgNum: -8823274 - Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01212 ] Object 0: handle = 0xd5b26f0000000010, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xff795e16 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].newLayout Image barrier Layout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL is not compatible with VkImage 0xd5b26f0000000010[] usage flags 0x20. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT (https://vulkan.lunarg.com/doc/view/1.3.224.0/linux/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01212)
    Objects: 1
        [0] 0xd5b26f0000000010, type: 10, name: NULL

VUID-vkCmdCopyImageToBuffer-srcImage-00186(ERROR / SPEC): msgNum: 805343557 - Validation Error: [ VUID-vkCmdCopyImageToBuffer-srcImage-00186 ] Object 0: handle = 0xd5b26f0000000010, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x30009145 | Invalid usage flag for VkImage 0xd5b26f0000000010[] used by vkCmdCopyImageToBuffer. In this case, VkImage should have VK_IMAGE_USAGE_TRANSFER_SRC_BIT set during creation. The Vulkan spec states: srcImage must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage flag (https://vulkan.lunarg.com/doc/view/1.3.224.0/linux/1.3-extensions/vkspec.html#VUID-vkCmdCopyImageToBuffer-srcImage-00186)
    Objects: 1
        [0] 0xd5b26f0000000010, type: 10, name: NULL
VUID-VkImageMemoryBarrier-oldLayout-01212(ERROR / SPEC): msgNum: -8823274 - Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01212 ] Object 0: handle = 0xd5b26f0000000010, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xff795e16 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].oldLayout Image barrier Layout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL is not compatible with VkImage 0xd5b26f0000000010[] usage flags 0x20. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT (https://vulkan.lunarg.com/doc/view/1.3.224.0/linux/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01212)
    Objects: 1
        [0] 0xd5b26f0000000010, type: 10, name: NULL

VUID-VkImageMemoryBarrier-oldLayout-01212(ERROR / SPEC): msgNum: -8823274 - Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01212 ] Object 0: handle = 0xd175b40000000013, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xff795e16 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].newLayout Image barrier Layout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL is not compatible with VkImage 0xd175b40000000013[] usage flags 0x4. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT (https://vulkan.lunarg.com/doc/view/1.3.224.0/linux/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01212)
    Objects: 1
        [0] 0xd175b40000000013, type: 10, name: NULL
VUID-vkCmdCopyImageToBuffer-srcImage-00186(ERROR / SPEC): msgNum: 805343557 - Validation Error: [ VUID-vkCmdCopyImageToBuffer-srcImage-00186 ] Object 0: handle = 0xd175b40000000013, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x30009145 | Invalid usage flag for VkImage 0xd175b40000000013[] used by vkCmdCopyImageToBuffer. In this case, VkImage should have VK_IMAGE_USAGE_TRANSFER_SRC_BIT set during creation. The Vulkan spec states: srcImage must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage flag (https://vulkan.lunarg.com/doc/view/1.3.224.0/linux/1.3-extensions/vkspec.html#VUID-vkCmdCopyImageToBuffer-srcImage-00186)
    Objects: 1
        [0] 0xd175b40000000013, type: 10, name: NULL
VUID-VkImageMemoryBarrier-oldLayout-01212(ERROR / SPEC): msgNum: -8823274 - Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01212 ] Object 0: handle = 0xd175b40000000013, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xff795e16 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].oldLayout Image barrier Layout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL is not compatible with VkImage 0xd175b40000000013[] usage flags 0x4. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT (https://vulkan.lunarg.com/doc/view/1.3.224.0/linux/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01212)
    Objects: 1
        [0] 0xd175b40000000013, type: 10, name: NULL
```

**Comment by bradgrantham-lunarg** [comment]
```
#0  __GI_raise (sig=sig@entry=5) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffeef62a4e in MessengerBreakCallback (message_severity=<optimized out>, message_type=<optimized out>, 
    callback_data=<optimized out>, user_data=<optimized out>)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/vk_layer_logging.h:802
#2  0x00007fffeeb08df6 in debug_log_msg (layer_prefix=0x7fffef3b6daa "Validation", text_vuid=<optimized out>, message=<optimized out>, 
    objects=..., msg_flags=<optimized out>, debug_data=<optimized out>)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/vk_layer_logging.h:479
#3  LogMsgLocked (debug_data=<optimized out>, msg_flags=msg_flags@entry=8, objects=..., 
    vuid_text="VUID-VkImageMemoryBarrier-oldLayout-01212", err_msg=<optimized out>)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/vk_layer_logging.h:739
#4  0x00007fffeeb945bd in ValidationObject::LogError<VkImage_T*> (this=0x1149d80, src_object=0xd5b26f0000000010, 
    vuid_text="VUID-VkImageMemoryBarrier-oldLayout-01212", format=<optimized out>)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/generated/chassis.h:3687
#5  0x00007fffeec3621c in CoreChecks::ValidateBarrierLayoutToImageUsage (this=this@entry=0x1149d80, loc=..., image=0xd5b26f0000000010, 
    layout=<optimized out>, usage_flags=usage_flags@entry=32)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/buffer_validation.cpp:804
#6  0x00007fffeec7363b in CoreChecks::ValidateBarriersToImages<VkImageMemoryBarrier> (this=this@entry=0x1149d80, outer_loc=..., 
    cb_state=cb_state@entry=0x1344970, imageMemoryBarrierCount=imageMemoryBarrierCount@entry=1, 
    pImageMemoryBarriers=pImageMemoryBarriers@entry=0x7fffffffc560)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/buffer_validation.cpp:832
#7  0x00007fffeec46a6c in CoreChecks::ValidateBarriers (this=this@entry=0x1149d80, outer_loc=..., cb_state=0x1344970, src_stage_mask=1, 
    dst_stage_mask=4096, memBarrierCount=<optimized out>, pMemBarriers=0x0, bufferBarrierCount=0, pBufferMemBarriers=0x0, 
    imageMemBarrierCount=1, pImageMemBarriers=0x7fffffffc560)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/buffer_validation.cpp:5540
#8  0x00007fffeeb515df in CoreChecks::PreCallValidateCmdPipelineBarrier (this=0x1149d80, commandBuffer=0x116e4a0, 
    srcStageMask=<optimized out>, dstStageMask=<optimized out>, dependencyFlags=<optimized out>, memoryBarrierCount=<optimized out>, 
    pMemoryBarriers=0x0, bufferMemoryBarrierCount=0, pBufferMemoryBarriers=0x0, imageMemoryBarrierCount=1, 
    pImageMemoryBarriers=0x7fffffffc560) at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/core_validation.cpp:11150
#9  0x00007fffee976c37 in vulkan_layer_chassis::CmdPipelineBarrier (commandBuffer=<optimized out>, srcStageMask=<optimized out>, 
    dstStageMask=<optimized out>, dependencyFlags=<optimized out>, memoryBarrierCount=<optimized out>, pMemoryBarriers=<optimized out>, 
    bufferMemoryBarrierCount=0, pBufferMemoryBarriers=0x0, imageMemoryBarrierCount=1, pImageMemoryBarriers=0x7fffffffc560)
    at /vulkan-sdk/1.3.224.0/source/Vulkan-ValidationLayers/layers/generated/chassis.cpp:3527
#10 0x00007fffed6439f0 in gfxrecon::encode::VulkanStateWriter::ProcessImageMemory (this=this@entry=0x7fffffffc8e0, 
    device_wrapper=device_wrapper@entry=0x11693f0, image_snapshot_info=std::vector of length 2, capacity 2 = {...}, 
--Type <RET> for more, q to quit, c to continue without paging--
    queue_family_index=queue_family_index@entry=0, queue=queue@entry=0xea6e80, command_buffer=command_buffer@entry=0x116e4a0, 
    staging_buffer=0x980b0000000002e, staging_memory=0x4b7df1000000002f, is_staging_memory_coherent=true, state_table=...)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/vulkan_state_writer.cpp:1317
#11 0x00007fffed645d39 in gfxrecon::encode::VulkanStateWriter::WriteResourceMemoryState (this=this@entry=0x7fffffffc8e0, state_table=...)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/vulkan_state_writer.cpp:1861
#12 0x00007fffed646d88 in gfxrecon::encode::VulkanStateWriter::WriteState (this=this@entry=0x7fffffffc8e0, state_table=..., 
    frame_number=frame_number@entry=332) at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/vulkan_state_writer.cpp:136
#13 0x00007fffed625bc9 in gfxrecon::encode::VulkanStateTracker::WriteState (frame_number=332, writer=0x7fffffffc8e0, this=0xdca600)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/vulkan_state_tracker.h:60
#14 gfxrecon::encode::VulkanCaptureManager::WriteTrackedState (this=<optimized out>, file_stream=<optimized out>, thread_id=<optimized out>)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/vulkan_capture_manager.cpp:87
#15 0x00007fffed6e8bc8 in gfxrecon::encode::CaptureManager::CheckStartCaptureForTrackMode (this=0xdccc20)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/capture_manager.cpp:533
#16 0x00007fffed6e8c65 in gfxrecon::encode::CaptureManager::EndFrame (this=this@entry=0xdccc20)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/capture_manager.cpp:588
#17 0x00007fffed67a60a in gfxrecon::encode::VulkanCaptureManager::PostProcess_vkQueuePresentKHR (pPresentInfo=0x7fffffffcb60, queue=0xe32d20, 
    result=VK_SUCCESS, this=<optimized out>) at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/vulkan_capture_manager.h:453
#18 gfxrecon::encode::CustomEncoderPostCall<(gfxrecon::format::ApiCallId)69806>::Dispatch<VkQueue_T*, VkPresentInfoKHR const*> (
    result=VK_SUCCESS, manager=<optimized out>)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/encode/custom_vulkan_encoder_commands.h:249
#19 gfxrecon::encode::QueuePresentKHR (queue=0xe32d20, pPresentInfo=0x7fffffffcb60)
    at /vulkan-sdk/1.3.224.0/source/gfxreconstruct/framework/generated/generated_vulkan_api_call_encoders.cpp:6629
#20 0x000000000040476b in demo_draw (demo=0x7fffffffd000) at /vulkan-sdk/1.3.224.0/source/Vulkan-Tools/cube/cube.c:1192
#21 demo_run_xcb (demo=0x7fffffffd000) at /vulkan-sdk/1.3.224.0/source/Vulkan-Tools/cube/cube.c:2747
#22 main (argc=<optimized out>, argv=<optimized out>) at /vulkan-sdk/1.3.224.0/source/Vulkan-Tools/cube/cube.c:4316
```

**Comment by locke-lunarg** [comment]
Windows and capture specific frames also happen it.
